# SPC700 Integration Test ROM
# Build with shared SNES build system.

PROJECT_NAME = spc700-testrom
BUILD_DIR = build

SHARED_BUILD_DIR = ../../shared/build
SHARED_SRC_DIR = ../../shared/src
SHARED_PORT_DIR = ../../shared/port

include $(SHARED_BUILD_DIR)/shared-config.mk
