; FamiStudio music data
.section .prg_rom_7,"a"
.globl music_data_untitled
; This file is for the FamiStudio Sound Engine and was generated by FamiStudio
; Required flags for Untitled:



music_data_untitled:
	.byte 1
	.word .Linstruments
	.word .Lsamples-4
; 00 : Song 1
	.word .Lsong0ch0
	.word .Lsong0ch1
	.word .Lsong0ch2
	.word .Lsong0ch3
	.word .Lsong0ch4
	.word .Ltempo_env_1_mid
	.byte 0, 0




.Linstruments:
	.word .Lenv6,.Lenv5,.Lenv8,.Lenv3 ; 00 : Drums low V
	.word .Lenv12,.Lenv5,.Lenv8,.Lenv0 ; 01 : Drums
	.word .Lenv14,.Lenv5,.Lenv7,.Lenv0 ; 02 : Celeste title lead
	.word .Lenv10,.Lenv5,.Lenv7,.Lenv0 ; 03 : Celeste title lead soft
	.word .Lenv4,.Lenv5,.Lenv8,.Lenv0 ; 04 : Drums loud
	.word .Lenv11,.Lenv5,.Lenv2,.Lenv0 ; 05 : Bass Drum
	.word .Lenv13,.Lenv5,.Lenv9,.Lenv1 ; 06 : Bass line

.Lenv0:
	.byte $00,$c0,$7f,$00,$02
.Lenv1:
	.byte $80,$c0,$c0,$c0,$c0,$c0,$c0,$c0,$c0,$c0,$c0,$c0,$c0,$c0,$c0,$c0,$c0,$c0,$c0,$c0,$bf,$bf,$bf,$c0,$c0,$c0,$c1,$c1,$c1,$c0,$c0,$c0,$00,$14
.Lenv2:
	.byte $c3,$7f,$00,$00
.Lenv3:
	.byte $00,$c0,$c3,$c9,$cf,$d4,$d9,$e2,$ee,$ff,$00,$09
.Lenv4:
	.byte $00,$cf,$02,$ce,$cc,$ca,$c7,$c4,$c2,$c0,$00,$09
.Lenv5:
	.byte $c0,$7f,$00,$01
.Lenv6:
	.byte $00,$c4,$c4,$c3,$c3,$c2,$c2,$c1,$c1,$c0,$00,$09
.Lenv7:
	.byte $7f,$00,$00
.Lenv8:
	.byte $c2,$7f,$00,$00
.Lenv9:
	.byte $c1,$7f,$00,$00
.Lenv10:
	.byte $00,$c6,$c6,$c5,$c2,$c1,$06,$c0,$04,$c1,$c4,$c4,$c3,$c2,$c1,$c0,$00,$0f
.Lenv11:
	.byte $00,$cd,$02,$cc,$cb,$c9,$c7,$c5,$c3,$c2,$c2,$c1,$05,$c0,$03,$c1,$c2,$c4,$c5,$02,$c4,$c2,$00,$15
.Lenv12:
	.byte $00,$c6,$c6,$c5,$c4,$c3,$c1,$c0,$00,$07
.Lenv13:
	.byte $00,$cd,$7f,$00,$02
.Lenv14:
	.byte $00,$cf,$cd,$c9,$c5,$c2,$c1,$05,$c0,$04,$c3,$c8,$c8,$c6,$c3,$c1,$c0,$00,$10

.Lsamples:

.Ltempo_env_1_mid:
	.byte $03,$05,$80

.Lsong0ch0:
	.byte $84
.Lsong0ref2:
	.byte $3d, $ad, $00, $8d, $3d, $9d, $38, $9d, $3b, $ad, $00, $8d, $3b, $ad, $00, $8d, $48, $36, $bd, $36, $bd, $00, $9d, $34
	.byte $bd, $34, $9d, $48, $36, $bd, $36, $bd, $38, $9d, $34, $9d, $34, $ad, $00, $8d, $48, $3b, $bd, $3b, $9d, $34, $cd, $00
	.byte $8d, $34, $ad, $00, $8d, $48
	.byte $41, $32
	.word .Lsong0ref2
	.byte $48
	.byte $41, $32
	.word .Lsong0ref2
	.byte $48
	.byte $41, $32
	.word .Lsong0ref2
	.byte $42
	.word .Lsong0ch0
.Lsong0ch1:
.Lsong0ref70:
	.byte $00, $8d, $84, $3d, $9d, $86, $31, $ad, $00, $8d, $84, $38, $8d, $00, $8d, $3b, $9d, $86, $2f, $9d, $84, $3b, $9d, $86
	.byte $2f, $8d, $00, $8d, $84, $36, $9d, $86, $2a, $9d, $84, $36, $ad, $00, $8d, $36, $9d, $34, $9d, $86, $28, $ad, $00, $8d
	.byte $84, $36, $9d, $86, $2a, $9d, $84, $36, $ad, $00, $8d, $38, $8d, $00, $8d, $34, $9d, $34, $9d, $86, $28, $8d, $00, $8d
	.byte $84, $3b, $9d, $3b, $9d, $2f, $9d, $34, $9d, $34, $9d, $86, $28, $9d, $84, $34, $9d, $86, $28, $8d
	.byte $41, $4a
	.word .Lsong0ref70
	.byte $41, $4a
	.word .Lsong0ref70
	.byte $41, $4a
	.word .Lsong0ref70
	.byte $42
	.word .Lsong0ch1
.Lsong0ch2:
	.byte $8c
.Lsong0ref175:
	.byte $19, $ed, $00, $8d, $19, $ed, $00, $8d, $1e, $cd, $00, $8d, $17, $cd, $00, $8d, $17, $bd, $12, $cd, $00, $8d, $14, $cd
	.byte $00, $8d, $1c, $bd, $19, $ff, $ad, $00, $8d, $19, $ad, $00, $8d
	.byte $41, $25
	.word .Lsong0ref175
	.byte $41, $25
	.word .Lsong0ref175
	.byte $41, $25
	.word .Lsong0ref175
	.byte $42
	.word .Lsong0ch2
.Lsong0ch3:
	.byte $80
.Lsong0ref225:
	.byte $22, $8d, $1c, $8d, $82, $20, $8d, $22, $8d, $1b, $8d, $80, $23, $8d, $82, $18, $8d, $00, $9d, $1c, $8d, $1e, $8d, $1c
	.byte $8d, $18, $8d, $00, $8d, $22, $8d, $80, $23, $8d, $88, $18, $8d, $80, $23, $8d, $88, $18, $8d, $00, $8d, $80, $23, $8d
	.byte $82, $1d, $8d, $16, $8d, $80, $1f, $8d, $82, $18, $8d, $00, $8d, $8a, $14, $bd, $82, $1e, $8d, $80, $20, $8d
	.byte $41, $38
	.word .Lsong0ref225
	.byte $41, $38
	.word .Lsong0ref225
	.byte $41, $38
	.word .Lsong0ref225
	.byte $41, $38
	.word .Lsong0ref225
	.byte $41, $38
	.word .Lsong0ref225
	.byte $41, $38
	.word .Lsong0ref225
	.byte $41, $38
	.word .Lsong0ref225
	.byte $42
	.word .Lsong0ch3
.Lsong0ch4:
.Lsong0ref319:
	.byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
	.byte $41, $10
	.word .Lsong0ref319
	.byte $42
	.word .Lsong0ch4
