"""pySnesDevTools - SNES homebrew asset converters (Pillow-only).

High-level API used by each project's `convert.py`. Every converter writes a
C `.inc` fragment to `output` and returns that path.

Image converters. `graphics` emits tile (character) data in raster order
(fonts, CHR sheets); `sprite` orders tiles for a single hardware OBJ of a given
size; `sprite_sheet` does the same for an N-frame animation strip; `background`
lays the image out as a tilemap; `collision` turns a mask PNG into a per-cell
solid table. All image converters take `bpp`. A font is
`graphics(bpp=1, palette=False)`.

    import pySnesDevTools as snes

    # one hardware OBJ sprite (tiles ordered for the OBJ char grid)
    snes.sprite("biker.png", "build/assets/biker.inc", symbol="biker",
                size="32x32", bpp=4)

    # an OBJ animation strip: frame k at CHARNUM k * <symbol>_STEP
    snes.sprite_sheet("player.png", "build/assets/player.inc", symbol="player",
                      frame="16x16", bpp=4)

    # tile graphics in raster order, no tilemap (fonts, CHR sheets)
    snes.graphics("snesfont.png", "build/assets/font.inc", symbol="font",
                  bpp=1, palette=False)

    # a background layer: tiles + tilemap + palette
    snes.background("school.png", "build/assets/school.inc", symbol="school", bpp=4)
    snes.background("bg_001.png", "build/assets/bg.inc", symbol="bg", bpp=4,
                    palette="per_scanline")   # HDMA per-scanline palette table

    # a per-8x8-cell solid table for tile collision (white = solid)
    snes.collision("level_col.png", "build/assets/levelcol.inc", symbol="level")

    # parse a Tiled .tmx map (layout + tile properties + object spawns)
    m = snes.load_tmx("level.tmx")

Emitted C symbols are `<symbol>_chr` (tiles), `<symbol>_pal` (palette),
`<symbol>_map` (tilemap), `<symbol>_col` (collision); `sprite_sheet` defines
`<symbol>_FRAMES/_STEP/_TILES`, `collision` defines `<symbol>_COLS/_ROWS`, and
`background(palette="per_scanline")` defines `SCANLINE_COUNT`. `raw_binary`
emits a bare `<symbol>`.
"""

import os

from . import bg as _bg
from . import convert as _convert
from . import decode as _decode
from . import emit as _emit
from .tiled import load_tmx


def _write(output, result):
    arrays, defines = result
    parent = os.path.dirname(output)
    if parent:
        os.makedirs(parent, exist_ok=True)
    _emit.write_inc(output, arrays, defines,
                    comment="Generated by pySnesDevTools - do not edit")
    return output


def graphics(image, output, symbol, bpp=4, palette=True):
    """Tile graphics only (no tilemap): <symbol>_chr [+ <symbol>_pal].

    Tiles stay in sheet (raster) order -- right for fonts and CHR sheets. For a
    hardware OBJ use sprite(), which orders tiles for the OBJ char grid.
    """
    return _write(output, _convert.graphics(image, symbol, bpp, palette))


def sprite(image, output, symbol, size="32x32", bpp=4, palette=True, section=None):
    """One hardware OBJ sprite, laid out for the 16-tile-wide OBJ char grid.

    size is a SNES OBJ size string: "8x8", "16x16", "32x32", "64x64", "16x32"
    or "32x64". A source of a different pixel size is auto-resized to it with
    nearest-neighbour, so one piece of art can drive several OBJ sizes. Unlike
    graphics() (raster order), tiles are arranged with each tile-row padded to
    the 16-tile char stride so a clean square PNG displays correctly at a
    16-aligned char base. Emits <symbol>_chr [+ <symbol>_pal].

    section: optional placement annotation emitted before the <symbol>_chr
    array (e.g. "PORT_DATA_BANK1" to move a large sprite out of bank 0).
    """
    arrays, defines = _convert.sprite(image, symbol, size, bpp, palette)
    if section:
        for a in arrays:
            if a["name"].endswith("_chr"):
                a["prefix"] = section
    return _write(output, (arrays, defines))


def background(image, output, symbol, bpp=4, palette="single", layout="screens"):
    """A background layer: deduped tiles + tilemap + palette.

    Emits <symbol>_chr, <symbol>_map, <symbol>_pal.
    palette: "single" (one 2**bpp-colour palette) or "per_scanline" (a
        16-colour palette per scanline, swapped at runtime via HDMA; 4bpp
        only, also defines SCANLINE_COUNT).
    layout: how the tilemap is arranged in VRAM/ROM.
        "screens" (default) splits images larger than one 32x32 screen into
        SNES screen blocks (up to 64x64 tiles / 512x512 px) -- a map that lives
        in VRAM whole.
        "columns" emits the tilemap column-major and unsplit, for a map too
        wide for VRAM that the C side streams in one column at a time while
        scrolling (single palette only; column geometry comes from the matching
        collision() output's <symbol>_ROWS / <symbol>_COLS).
    """
    if layout == "columns":
        if palette != "single":
            raise ValueError("layout='columns' requires palette='single'")
        return _write(output, _bg.columns(image, symbol, bpp))
    if layout != "screens":
        raise ValueError("layout must be 'screens' or 'columns'")
    if palette == "per_scanline":
        if bpp != 4:
            raise ValueError("per_scanline palettes require bpp=4")
        return _write(output, _bg.scanline(image, symbol))
    if palette != "single":
        raise ValueError("palette must be 'single' or 'per_scanline'")
    return _write(output, _bg.single(image, symbol, bpp))


def sprite_sheet(image, output, symbol, frame="16x16", frames=None, bpp=4,
                 palette=True):
    """An OBJ animation strip: N frames in one VRAM block, each independently
    addressable by CHARNUM.

    The source is a horizontal strip of `frame`-sized frames (a SNES OBJ size
    string). Frame k sits at OAM CHARNUM k * <symbol>_STEP. Emits <symbol>_chr
    [+ <symbol>_pal] and the defines <symbol>_FRAMES, <symbol>_STEP and
    <symbol>_TILES (CHARNUM base for the next block).
    """
    return _write(output, _convert.sprite_sheet(image, symbol, frame, frames,
                                                 bpp, palette))


def collision(image, output, symbol, threshold=128):
    """A per-cell solid table from a black/white collision-mask PNG.

    Each 8x8 cell becomes one byte in <symbol>_col (row-major): 1 where the
    cell is white (>= threshold brightness), else 0. Also defines
    <symbol>_COLS / <symbol>_ROWS. The mask must match the background's size.
    """
    return _write(output, _convert.collision(image, symbol, threshold))


def raw_binary(binary, output, symbol):
    """Raw file bytes -> one unsigned char array."""
    return _write(output, _convert.raw_binary(binary, symbol))


def decode(header, output, symbol, mode, bpp=4, tiles_x=32, columns=8):
    """Reconstruct a source PNG from existing C arrays (reverse step).

    mode: "background" (reads <symbol>_chr/_pal/_map) or "graphics" (reads
    <symbol>_chr, and <symbol>_pal if present).
    """
    with open(header) as f:
        text = f.read()
    if mode == "background":
        _decode.decode_bg(text, symbol, tiles_x, output)
    elif mode == "graphics":
        has_pal = (symbol + "_pal") in text
        _decode.decode_sheet(text, symbol + "_chr",
                             symbol + "_pal" if has_pal else None,
                             bpp, columns, output)
    else:
        raise ValueError("unknown decode mode %r" % mode)
    return output
