"""Command-line entry point for pySnesDevTools.

Runs either as a module (`python -m pySnesDevTools ...`) or as a plain script
by path (`python .../pySnesDevTools/snescli.py ...`); the latter bootstraps
sys.path so the package imports resolve without installation.
"""

import argparse
import os
import sys

if __package__ in (None, ""):
    sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
    from pySnesDevTools import bg, convert, decode, emit
else:
    from . import bg, convert, decode, emit


def _write(out_path, result):
    arrays, defines = result
    parent = os.path.dirname(out_path)
    if parent:
        os.makedirs(parent, exist_ok=True)
    emit.write_inc(out_path, arrays, defines,
                   comment="Generated by pySnesDevTools - do not edit")


def main(argv=None):
    p = argparse.ArgumentParser(prog="pySnesDevTools",
                                description="SNES asset converters")
    sub = p.add_subparsers(dest="cmd")
    sub.required = True

    sp = sub.add_parser("bg", help="4bpp background: tiles + tilemap + palette")
    sp.add_argument("image")
    sp.add_argument("-o", "--output", required=True)
    sp.add_argument("--symbol", required=True)
    sp.add_argument("--scanline-palettes", action="store_true",
                    help="emit a per-scanline palette table (HDMA effect)")

    sp = sub.add_parser("sprite", help="4bpp sprite tiles (sheet order) + palette")
    sp.add_argument("image")
    sp.add_argument("-o", "--output", required=True)
    sp.add_argument("--symbol", required=True)

    sp = sub.add_parser("font", help="1bpp 8x8 tiles from a 2-colour image")
    sp.add_argument("image")
    sp.add_argument("-o", "--output", required=True)
    sp.add_argument("--symbol", required=True)

    sp = sub.add_parser("bin2c", help="raw bytes -> C array")
    sp.add_argument("binary")
    sp.add_argument("-o", "--output", required=True)
    sp.add_argument("--symbol", required=True)

    sp = sub.add_parser("decode", help="reconstruct a source PNG from C arrays")
    sp.add_argument("header")
    sp.add_argument("-o", "--output", required=True)
    sp.add_argument("--symbol", required=True)
    sp.add_argument("--mode", choices=["bg", "sprite", "font"], required=True)
    sp.add_argument("--tiles-x", type=int, default=32)
    sp.add_argument("--columns", type=int, default=8)

    args = p.parse_args(argv)

    if args.cmd == "bg":
        fn = bg.convert_scanline if args.scanline_palettes else bg.convert_single
        _write(args.output, fn(args.image, args.symbol))
    elif args.cmd == "sprite":
        _write(args.output, convert.convert_sprite(args.image, args.symbol))
    elif args.cmd == "font":
        _write(args.output, convert.convert_font(args.image, args.symbol))
    elif args.cmd == "bin2c":
        _write(args.output, convert.convert_bin2c(args.binary, args.symbol))
    elif args.cmd == "decode":
        with open(args.header) as f:
            text = f.read()
        if args.mode == "bg":
            decode.decode_bg(text, args.symbol, args.tiles_x, args.output)
        elif args.mode == "sprite":
            decode.decode_sheet(text, args.symbol + "_pic", args.symbol + "_clr",
                                4, args.columns, args.output)
        else:
            decode.decode_sheet(text, args.symbol, None, 1, args.columns,
                                args.output)
    return 0


if __name__ == "__main__":
    sys.exit(main())
