
ROM_NAME      = Print_Test
CONFIG        = LOROM_1MBit
API_MODULES   = reset-snes sfc-header math block text text8x8
API_DIR       = ../..
SOURCE_DIR    = .
RESOURCES_DIR = resources

include $(API_DIR)/Makefile.in
