#ifndef RESOURCES_H
#define RESOURCES_H

// Auto-generated by convert_resources.py
// Forward declarations for resource data
// The actual definitions are in the individual .h files
// Include them directly in files that need them to avoid multiple definition errors

// Background resources
extern const unsigned short backgroundPalette[];
extern const unsigned char backgroundTiles[];
extern const unsigned short backgroundMap[];
extern const unsigned short controlsPalette[];
extern const unsigned char controlsTiles[];
extern const unsigned short controlsMap[];
extern const unsigned short splashPalette[];
extern const unsigned char splashTiles[];
extern const unsigned short splashMap[];

// Tiles resources
extern const unsigned short interactiveTilesPalette[];
extern const unsigned char interactiveTilesTiles[];

// Metasprite resources
extern const unsigned short businessManPalette[];
extern const unsigned char businessManTiles[];
extern const unsigned short playerPalette[];
extern const unsigned char playerTiles[];
extern const unsigned short strikeAnimationsPalette[];
extern const unsigned char strikeAnimationsTiles[];

// Size constants are defined in the individual generated header files
// Include the specific resource headers to access their size constants:
// - resources/images4bpp/background.h defines BACKGROUNDTILES_SIZE, BACKGROUNDMAP_SIZE, etc.
// - resources/images4bpp/splash.h defines SPLASHTILES_SIZE, SPLASHMAP_SIZE, etc.
// - resources/images4bpp/controls.h defines CONTROLSTILES_SIZE, CONTROLSMAP_SIZE, etc.
// - etc.

// Metasprite frame constants (forward declarations - include metasprite_data.h in files that need frame tables)
// Frame index constants are defined in resources/metasprites/metasprite_data.h
// Frame tables: player[], businessMan[], fightingCloud[], etc.

#endif // RESOURCES_H
