
ROM_NAME      = Simon_Says
CONFIG        = LOROM_1MBit_copyright
API_MODULES   = reset-snes sfc-header cpu-usage screen controller block math random snesgss
API_DIR       = ../..
SOURCE_DIR    = .
RESOURCES_DIR = resources

include $(API_DIR)/Makefile.in

