#!/usr/bin/env python
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
MAP_PATH = ROOT / "build" / "mainBankZero_llvm-mos.map"
OUT_PATH = ROOT / "build" / "mesen_symbols.lua"

REQUIRED = [
    "GLOBAL_ActiveLevel",
    "GLOBAL_PlayerData",
    "GLOBAL_OBJList",
    "GLOBAL_FrameCount",
    "GLOBAL_MonumentTextDisplayed",
    "GLOBAL_MonumentCurLineNum",
    "GLOBAL_MonumentCurLineCharCount",
    "s_monumentTextTick",
]


def parse_symbols(map_text: str):
    found = {}
    # Map lines look like:
    #  268      268      27a     1         ...:(.bss.GLOBAL_ActiveLevel)
    pattern = re.compile(
        r"^\s*([0-9a-fA-F]+)\s+[0-9a-fA-F]+\s+[0-9a-fA-F]+\s+\d+\s+.*\((?:\.bss|\.data)\.([A-Za-z0-9_]+)\)\s*$"
    )
    for line in map_text.splitlines():
        m = pattern.match(line)
        if not m:
            continue
        addr = int(m.group(1), 16)
        sym = m.group(2)
        if sym in REQUIRED and sym not in found:
            found[sym] = addr
    return found


def main():
    if not MAP_PATH.exists():
        raise SystemExit(f"Map file not found: {MAP_PATH}")

    text = MAP_PATH.read_text(encoding="utf-8", errors="replace")
    syms = parse_symbols(text)

    missing = [s for s in REQUIRED if s not in syms]
    if missing:
        raise SystemExit(f"Missing symbols in map: {', '.join(missing)}")

    lines = [
        "-- Auto-generated by scripts/gen_mesen_symbols.py",
        "return {",
        "  WRAM_BASE = 0x7E0000,",
    ]
    for sym in REQUIRED:
        lines.append(f"  {sym} = 0x7E{syms[sym]:04X},")
    lines.extend([
        "}",
        "",
    ])
    OUT_PATH.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {OUT_PATH}")


if __name__ == "__main__":
    main()
