// Level 4 animation — separate compilation unit (no LTO) to respect bank section attributes.
#define __NES__
#include "port.h"
#include <stdint.h>
#include <string.h>
#include <mapper.h>
#ifndef _WIN32
#include <neslib.h>
#endif

#include "../../python/level4_anim_data.h"

#define PPU_CTRL   (*(volatile uint8_t *)0x2000)
#define PPU_STATUS (*(volatile uint8_t *)0x2002)
#define PPU_ADDR   (*(volatile uint8_t *)0x2006)
#define PPU_DATA   (*(volatile uint8_t *)0x2007)

// Shared state with nes.c (defined there, extern here)
extern volatile uint8_t s_inputState;
extern uint8_t palette_ram[32];

// Title screen shared variables (reused for level animation)
extern uint8_t  s_ppu_write_count;
extern uint8_t  s_ppu_write_cursor;
extern uint8_t  s_attr_buf[64];
extern uint8_t  s_delta_active;
extern uint8_t  s_flush_rate;

// Level animation state
uint8_t s_levelAnimActive;
uint8_t s_levelAnimVariant;
uint8_t s_levelAnimFrame;
uint8_t s_levelAnimTimer;
uint8_t s_laSelectPrev;


extern struct sPlayerData GLOBAL_PlayerData;
extern OBJ_DATA GLOBAL_OBJList[];

// Inline flush state — compile-time constant PPU writes stored as code in ROM banks 8/9.
// No RAM buffers needed. Just track which delta/chunk to execute next.
static uint8_t s_flushDeltaIdx;   // Which delta (0-11)
static uint8_t s_flushChunkIdx;   // Which chunk within the delta
static uint8_t s_flushTotalChunks; // Total chunks for current delta

typedef void (*flush_fn_t)(void);

// Extern: function pointer tables (in banks 8/9, generated by convert_level_anim.py)
extern const flush_fn_t la_flush_table_a[];
extern const uint16_t la_flush_offsets_a[];
extern const uint8_t la_chunk_counts_a[];
extern const flush_fn_t la_attr_table_a[];

extern const flush_fn_t la_flush_table_b[];
extern const uint16_t la_flush_offsets_b[];
extern const uint8_t la_chunk_counts_b[];
extern const flush_fn_t la_attr_table_b[];

#define LEVEL4_ANIM_BANK 4
#define LEVEL4_ANIM_SPEED 5  // 30fps / 5 = 6fps (20 writes/chunk needs 5 vblanks to flush)
// During gameplay, vblank budget is shared with BG tile writes, input, scroll, etc.
// Title screen uses 34/vblank but has no other work. Gameplay needs a lower limit.
// 14 tiles × ~26 cycles = ~364 cycles, attrs = ~280 cycles. Safe within remaining budget.
// With bank-switch overhead eliminated on idle frames and reduced on active frames,
// we can afford more writes. 10 tiles × ~27 cycles = ~270 cycles.
#define LA_MAX_WRITES_PER_VBLANK 10
#define LA_ATTR_MERGE_THRESHOLD 0  // Always defer attrs to separate vblank

// --- Bank 4 functions ---

__attribute__((section(".prg_rom_4.text"), noinline))
static void la_decode_rle(const unsigned char *rle, uint16_t addr, uint16_t max) {
    vram_adr(addr);
    uint16_t written = 0, idx = 0;
    while (written < max) {
        uint8_t cnt = rle[idx++];
        if (cnt == 0xFF) break;
        uint8_t tile = rle[idx++];
        for (uint8_t i = 0; i <= cnt && written < max; i++, written++)
            vram_put(tile);
    }
}

__attribute__((section(".prg_rom_4.text"), noinline))
static void la_write_attrs(uint16_t addr, const unsigned char *a) {
    vram_adr(addr);
    for (uint8_t i = 0; i < 64; i++) vram_put(a[i]);
}

__attribute__((section(".prg_rom_4.text"), noinline))
static void la_load_frame0(uint8_t v) {
    if (v == 0) {
        la_decode_rle(level4_anim_nt0_rle_a, NTADR_A(0,0), 960);
        la_write_attrs(0x23C0, level4_anim_attr0_nt0_a);
        la_decode_rle(level4_anim_nt2_rle_a, 0x2800, 960);
        la_write_attrs(0x2BC0, level4_anim_attr0_nt2_a);
    } else {
        la_decode_rle(level4_anim_nt0_rle_b, NTADR_A(0,0), 960);
        la_write_attrs(0x23C0, level4_anim_attr0_nt0_b);
        la_decode_rle(level4_anim_nt2_rle_b, 0x2800, 960);
        la_write_attrs(0x2BC0, level4_anim_attr0_nt2_b);
    }
}

// Prepare all tile changes from a delta into the PPU buffer (single shot, buffer is large enough)
// Prepare delta — just record which delta to flush via inline code.
__attribute__((section(".prg_rom_4.text"), noinline))
static void la_prepare_delta(const unsigned char *delta) {
    uint16_t count = delta[0] | ((uint16_t)delta[1] << 8);
    s_flushDeltaIdx = s_levelAnimFrame;
    s_flushChunkIdx = 0;
    s_flushTotalChunks = ((uint8_t)count + LA_MAX_WRITES_PER_VBLANK - 1) / LA_MAX_WRITES_PER_VBLANK;
    s_delta_active = 1;
}

__attribute__((section(".prg_rom_4.text"), noinline))
static void la_apply_delta_full(const unsigned char *delta) {
    uint16_t idx = 0;
    uint16_t count = delta[idx] | ((uint16_t)delta[idx+1] << 8);
    idx += 2;
    for (uint16_t i = 0; i < count; i++) {
        uint16_t pos = delta[idx] | ((uint16_t)delta[idx+1] << 8);
        uint8_t tile = delta[idx+2]; idx += 3;
        uint16_t a = (pos < 960) ? (0x2000 + pos) : (0x2800 + pos - 960);
        PPU_ADDR = (uint8_t)(a >> 8); PPU_ADDR = (uint8_t)a; PPU_DATA = tile;
    }
    PPU_ADDR = 0x23; PPU_ADDR = 0xC0;
    for (uint8_t i = 0; i < 64; i++) PPU_DATA = delta[idx++];
    // Skip NT2 attributes (written once at init)
}

__attribute__((section(".prg_rom_4.text"), noinline))
void la_init_bank4(void) {
    extern const unsigned char game_chr_data[];

    s_levelAnimVariant = 0;
    s_levelAnimFrame = 0;
    s_levelAnimTimer = 0;

    // Write animation BG tiles to $1000 (sprite pattern table area).
    // During level 4, PPU_CTRL bit 4 is set so BG reads from $1000.
    // Game sprites continue reading from $0000 (untouched).
    vram_adr(0x1000);
    for (uint16_t i = 0; i < sizeof(level4_anim_chr_tiles); i++) {
        vram_put(level4_anim_chr_tiles[i]);
    }

    // Collapse tile CHR patterns are copied by port_LoadRoomData (fixed bank)
    // before this function is called, since we can't switch PRG banks from bank 4.

    la_load_frame0(0);
    for (uint8_t i = 0; i < 16; i++) palette_ram[i] = level4_anim_bg_palette[i];
    pal_bg(palette_ram);
}

__attribute__((section(".prg_rom_4.text"), noinline))
void la_advance_bank4(void) {
    uint8_t sel = s_inputState & PORT_INPUT_SELECT_MASK;
    uint8_t prev = s_laSelectPrev & PORT_INPUT_SELECT_MASK;
    s_laSelectPrev = s_inputState;
    if (sel && !prev) {
        s_levelAnimVariant ^= 1;
        s_delta_active = 0;
        ppu_off();
        la_load_frame0(s_levelAnimVariant);
        for (uint8_t f = 0; f < s_levelAnimFrame; f++) {
            if (s_levelAnimVariant == 0)
                la_apply_delta_full(&level4_anim_delta_a[level4_anim_delta_offsets_a[f]]);
            else
                la_apply_delta_full(&level4_anim_delta_b[level4_anim_delta_offsets_b[f]]);
        }
        ppu_on_all();
    }

    if (s_delta_active) return;  // Wait for flush to complete

    s_levelAnimTimer++;
    if (s_levelAnimTimer >= LEVEL4_ANIM_SPEED) {
        s_levelAnimTimer = 0;
        if (s_levelAnimVariant == 0)
            la_prepare_delta(&level4_anim_delta_a[level4_anim_delta_offsets_a[s_levelAnimFrame]]);
        else
            la_prepare_delta(&level4_anim_delta_b[level4_anim_delta_offsets_b[s_levelAnimFrame]]);
        s_levelAnimFrame++;
        if (s_levelAnimFrame >= LEVEL4_ANIM_FRAME_COUNT) s_levelAnimFrame = 0;
        if (s_levelAnimFrame == 0) {
            s_flush_rate = (s_ppu_write_count + LEVEL4_ANIM_SPEED - 1) / LEVEL4_ANIM_SPEED;
            if (s_flush_rate < 1) s_flush_rate = 1;
        }
    }
}

// --- Fixed bank flush: calls function pointer tables (banks 8/9) ---
// No branching in banked code — dispatch via flat function pointer array.

__attribute__((noinline))
void port_levelAnimFlush(void) {
    uint8_t bank = 8 + s_levelAnimVariant;
    set_prg_bank(bank);
    if (s_delta_active == 1) {
        // Lazy-load total chunks from the banked table on first chunk
        if (s_flushChunkIdx == 0) {
            if (s_levelAnimVariant == 0)
                s_flushTotalChunks = la_chunk_counts_a[s_flushDeltaIdx];
            else
                s_flushTotalChunks = la_chunk_counts_b[s_flushDeltaIdx];
        }

        if (s_levelAnimVariant == 0)
            la_flush_table_a[la_flush_offsets_a[s_flushDeltaIdx] + s_flushChunkIdx]();
        else
            la_flush_table_b[la_flush_offsets_b[s_flushDeltaIdx] + s_flushChunkIdx]();
        if (++s_flushChunkIdx >= s_flushTotalChunks)
            s_delta_active = 2;
    } else {
        if (s_levelAnimVariant == 0)
            la_attr_table_a[s_flushDeltaIdx]();
        else
            la_attr_table_b[s_flushDeltaIdx]();
        s_delta_active = 0;
    }
}

// --- Fixed bank trampoline ---

__attribute__((noinline))
void port_levelAnimAdvance(void) {
    if (!s_levelAnimActive || s_delta_active) return;
    set_prg_bank(LEVEL4_ANIM_BANK);
    la_advance_bank4();
    set_prg_bank(0);
}
