// Title screen flush wrapper — uses function pointer tables (no branching in banked code).
#include <stdint.h>
#include <mapper.h>

extern uint8_t s_delta_active;

typedef void (*flush_fn_t)(void);

// Function pointer tables (in banks 10/11, generated by convert_title_screen.py)
extern const flush_fn_t title_flush_table_a[];
extern const uint16_t title_flush_offsets_a[];
extern const uint8_t title_chunk_counts_a[];
extern const flush_fn_t title_attr_table_a[];

extern const flush_fn_t title_flush_table_b[];
extern const uint16_t title_flush_offsets_b[];
extern const uint8_t title_chunk_counts_b[];
extern const flush_fn_t title_attr_table_b[];

static uint8_t s_titleDeltaIdx;
static uint8_t s_titleChunkIdx;
static uint8_t s_titleTotalChunks;

void title_prepare_delta(uint8_t anim_frame, uint8_t tile_count) {
    s_titleDeltaIdx = anim_frame;
    s_titleChunkIdx = 0;
    // tile_count is still passed but we use chunk_counts tables for accuracy
    // (kept for API compatibility — caller doesn't need to change)
    s_titleTotalChunks = 0;  // Will be set from table in flush
    s_delta_active = 1;
}

void title_flush_ppu_writes(uint8_t variant) {
    if (!s_delta_active) return;

    uint8_t bank = 10 + variant;
    set_prg_bank(bank);

    if (s_delta_active == 1) {
        // Lazy-load total chunks from the banked table on first chunk
        if (s_titleChunkIdx == 0) {
            if (variant == 0)
                s_titleTotalChunks = title_chunk_counts_a[s_titleDeltaIdx];
            else
                s_titleTotalChunks = title_chunk_counts_b[s_titleDeltaIdx];
        }

        if (variant == 0)
            title_flush_table_a[title_flush_offsets_a[s_titleDeltaIdx] + s_titleChunkIdx]();
        else
            title_flush_table_b[title_flush_offsets_b[s_titleDeltaIdx] + s_titleChunkIdx]();

        if (++s_titleChunkIdx >= s_titleTotalChunks)
            s_delta_active = 2;
    } else {
        if (variant == 0)
            title_attr_table_a[s_titleDeltaIdx]();
        else
            title_attr_table_b[s_titleDeltaIdx]();
        s_delta_active = 0;
    }
    set_prg_bank(0);
}
