
ROM_NAME      = Timer
CONFIG        = LOROM_1MBit
API_MODULES   = reset-snes sfc-header math text block text8x8 text8x16
API_DIR       = ../..
SOURCE_DIR    = .
RESOURCES_DIR = resources

include $(API_DIR)/Makefile.in

