; This file is for the FamiTone2 library and was generated by FamiStudio
; Required flags for Untitled:

.export _music_data_untitled:=music_data_untitled

music_data_untitled:
	.byte 1
	.word @instruments
	.word @samples-3
; 00 : Song 1
	.word @song0ch0
	.word @song0ch1
	.word @song0ch2
	.word @song0ch3
	.word @song0ch4
	.word 307,256

.export music_data_untitled
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.byte $f0 ; 00 : Bass Drum
	.word @env0, @env5, @env5
	.byte $00
	.byte $70 ; 01 : Bass line
	.word @env8, @env5, @env3
	.byte $00
	.byte $30 ; 02 : Celeste title lead
	.word @env7, @env5, @env5
	.byte $00
	.byte $30 ; 03 : Celeste title lead soft
	.word @env4, @env5, @env5
	.byte $00
	.byte $b0 ; 04 : Drums
	.word @env6, @env5, @env5
	.byte $00
	.byte $b0 ; 05 : Drums loud
	.word @env1, @env5, @env5
	.byte $00
	.byte $b0 ; 06 : Drums low V
	.word @env9, @env5, @env2
	.byte $00

@env0:
	.byte $cd,$02,$cc,$cb,$c9,$c7,$c5,$c3,$c2,$c2,$c1,$05,$c0,$03,$c1,$c2,$c4,$c5,$02,$c4,$c2,$00,$14
@env1:
	.byte $cf,$02,$ce,$cc,$ca,$c7,$c4,$c2,$c0,$00,$08
@env2:
	.byte $c0,$c3,$c9,$cf,$d4,$d9,$e2,$ee,$ff,$00,$08
@env3:
	.byte $c0,$c0,$c0,$c0,$c0,$c0,$c0,$c0,$c0,$c0,$c0,$c0,$c0,$c0,$c0,$c0,$c0,$c0,$c0,$bf,$bf,$bf,$c0,$c0,$c0,$c1,$c1,$c1,$c0,$c0,$c0,$00,$13
@env4:
	.byte $c6,$c6,$c5,$c2,$c1,$06,$c0,$04,$c1,$c4,$c4,$c3,$c2,$c1,$c0,$00,$0e
@env5:
	.byte $c0,$7f,$00,$01
@env6:
	.byte $c6,$c6,$c5,$c4,$c3,$c1,$c0,$00,$06
@env7:
	.byte $cf,$cd,$c9,$c5,$c2,$c1,$05,$c0,$04,$c3,$c8,$c8,$c6,$c3,$c1,$c0,$00,$0f
@env8:
	.byte $cd,$7f,$00,$00
@env9:
	.byte $c4,$c4,$c3,$c3,$c2,$c2,$c1,$c1,$c0,$00,$08

@samples:

@song0ch0:
	.byte $fb, $01, $84
@song0ref4:
	.byte $7a, $ad, $00, $8d, $7a, $9d, $70, $9d, $76, $ad, $00, $8d, $76, $ad, $00, $8d, $6c, $bd, $6c, $bd, $00, $9d, $68, $bd
	.byte $68, $9d, $6c, $bd, $6c, $bd, $70, $9d, $68, $9d, $68, $ad, $00, $8d, $76, $bd, $76, $9d, $68, $cd, $00, $8d, $68, $ad
	.byte $00, $8d
	.byte $ff, $32
	.word @song0ref4
	.byte $ff, $32
	.word @song0ref4
	.byte $ff, $32
	.word @song0ref4
@song0ch0loop:
	.byte $00, $fd
	.word @song0ch0loop
@song0ch1:
@song0ref68:
	.byte $00, $8d, $84, $7a, $9d, $86, $62, $ad, $00, $8d, $84, $70, $8d, $00, $8d, $76, $9d, $86, $5e, $9d, $84, $76, $9d, $86
	.byte $5e, $8d, $00, $8d, $84, $6c, $9d, $86, $54, $9d, $84, $6c, $ad, $00, $8d, $6c, $9d, $68, $9d, $86, $50, $ad, $00, $8d
	.byte $84, $6c, $9d, $86, $54, $9d, $84, $6c, $ad, $00, $8d, $70, $8d, $00, $8d, $68, $9d, $68, $9d, $86, $50, $8d, $00, $8d
	.byte $84, $76, $9d, $76, $9d, $5e, $9d, $68, $9d, $68, $9d, $86, $50, $9d, $84, $68, $9d, $86, $50, $8d
	.byte $ff, $4a
	.word @song0ref68
	.byte $ff, $4a
	.word @song0ref68
	.byte $ff, $4a
	.word @song0ref68
@song0ch1loop:
	.byte $00, $fd
	.word @song0ch1loop
@song0ch2:
	.byte $82
@song0ref175:
	.byte $32, $ed, $00, $8d, $32, $ed, $00, $8d, $3c, $cd, $00, $8d, $2e, $cd, $00, $8d, $2e, $bd, $24, $cd, $00, $8d, $28, $cd
	.byte $00, $8d, $38, $bd, $32, $f9, $b3, $00, $8d, $32, $ad, $00, $8d
	.byte $ff, $25
	.word @song0ref175
	.byte $ff, $25
	.word @song0ref175
	.byte $ff, $25
	.word @song0ref175
@song0ch2loop:
	.byte $00, $fd
	.word @song0ch2loop
@song0ch3:
	.byte $8c
@song0ref227:
	.byte $5c, $8d, $50, $8d, $88, $58, $8d, $5c, $8d, $4e, $8d, $8c, $5e, $8d, $88, $48, $8d, $00, $9d, $50, $8d, $54, $8d, $50
	.byte $8d, $48, $8d, $00, $8d, $5c, $8d, $8c, $5e, $8d, $8a, $48, $8d, $8c, $5e, $8d, $8a, $48, $8d, $00, $8d, $8c, $5e, $8d
	.byte $88, $52, $8d, $44, $8d, $8c, $56, $8d, $88, $48, $8d, $00, $8d, $80, $40, $bd, $88, $54, $8d, $8c, $58, $8d
	.byte $ff, $38
	.word @song0ref227
	.byte $ff, $38
	.word @song0ref227
	.byte $ff, $38
	.word @song0ref227
	.byte $ff, $38
	.word @song0ref227
	.byte $ff, $38
	.word @song0ref227
	.byte $ff, $38
	.word @song0ref227
	.byte $ff, $38
	.word @song0ref227
@song0ch3loop:
	.byte $00, $fd
	.word @song0ch3loop
@song0ch4:
@song0ref323:
	.byte $f9, $f9, $8b, $f9, $f9, $8b, $f9, $f9, $8b, $f9, $f9, $8b
	.byte $ff, $0c
	.word @song0ref323
	.byte $ff, $0c
	.word @song0ref323
	.byte $ff, $0c
	.word @song0ref323
@song0ch4loop:
	.byte $00, $fd
	.word @song0ch4loop
