; Generated by snesdev-util 0.01 alpha

; MetaSpriteFrameSets
	; MetaSpriteFrame_player
	MetaSpriteFrame_player_standRight = 0
	MetaSpriteFrame_player_walkRight = 1
	MetaSpriteFrame_player_turnRight = 2
	MetaSpriteFrame_player_jumpRight = 3
	MetaSpriteFrame_player_fallRight = 4
	MetaSpriteFrame_player_pushButtonRight = 5
	MetaSpriteFrame_player_zappedRight = 6
	MetaSpriteFrame_player_standLeft = 7
	MetaSpriteFrame_player_walkLeft = 8
	MetaSpriteFrame_player_turnLeft = 9
	MetaSpriteFrame_player_jumpLeft = 10
	MetaSpriteFrame_player_fallLeft = 11
	MetaSpriteFrame_player_pushButtonLeft = 12
	MetaSpriteFrame_player_zappedLeft = 13
	; MetaSpriteFrame_npc
	MetaSpriteFrame_npc_normalStandRight = 0
	MetaSpriteFrame_npc_normalWalkRight = 1
	MetaSpriteFrame_npc_normalWaitRight = 2
	MetaSpriteFrame_npc_stressedStandRight = 3
	MetaSpriteFrame_npc_stressedWalkRight = 4
	MetaSpriteFrame_npc_stressedWaitRight = 5
	MetaSpriteFrame_npc_angryStandRight = 6
	MetaSpriteFrame_npc_angryWalkRight = 7
	MetaSpriteFrame_npc_angryWaitRight = 8
	MetaSpriteFrame_npc_fightingStandRight = 9
	MetaSpriteFrame_npc_fightingWalkRight = 10
	MetaSpriteFrame_npc_fightingWaitRight = 11
	MetaSpriteFrame_npc_normalStandLeft = 12
	MetaSpriteFrame_npc_normalWalkLeft = 13
	MetaSpriteFrame_npc_normalWaitLeft = 14
	MetaSpriteFrame_npc_stressedStandLeft = 15
	MetaSpriteFrame_npc_stressedWalkLeft = 16
	MetaSpriteFrame_npc_stressedWaitLeft = 17
	MetaSpriteFrame_npc_angryStandLeft = 18
	MetaSpriteFrame_npc_angryWalkLeft = 19
	MetaSpriteFrame_npc_angryWaitLeft = 20
	MetaSpriteFrame_npc_fightingStandLeft = 21
	MetaSpriteFrame_npc_fightingWalkLeft = 22
	MetaSpriteFrame_npc_fightingWaitLeft = 23
	; MetaSpriteFrame_fightingCloud
	MetaSpriteFrame_fightingCloud_frame0 = 0
	MetaSpriteFrame_fightingCloud_frame1 = 1
	MetaSpriteFrame_fightingCloud_frame2 = 2
	MetaSpriteFrame_fightingCloud_frame3 = 3
	MetaSpriteFrame_fightingCloud_frame4 = 4
	; MetaSpriteFrame_leftRight
	MetaSpriteFrame_leftRight_left = 0
	MetaSpriteFrame_leftRight_right = 1


.global MetaSpriteFrameTable

.global MetaSpriteFrameTable_elevator
.global MetaSprite_player
	.global MetaSprite_player_standRight
	.global MetaSprite_player_walkRight
	.global MetaSprite_player_turnRight
	.global MetaSprite_player_jumpRight
	.global MetaSprite_player_fallRight
	.global MetaSprite_player_pushButtonRight
	.global MetaSprite_player_zappedRight
	.global MetaSprite_player_standLeft
	.global MetaSprite_player_walkLeft
	.global MetaSprite_player_turnLeft
	.global MetaSprite_player_jumpLeft
	.global MetaSprite_player_fallLeft
	.global MetaSprite_player_pushButtonLeft
	.global MetaSprite_player_zappedLeft

.global MetaSpriteFrameTable_npcs
.global MetaSprite_businessMan
	.global MetaSprite_businessMan_normalStandRight
	.global MetaSprite_businessMan_normalWalkRight
	.global MetaSprite_businessMan_normalWaitRight
	.global MetaSprite_businessMan_stressedStandRight
	.global MetaSprite_businessMan_stressedWalkRight
	.global MetaSprite_businessMan_stressedWaitRight
	.global MetaSprite_businessMan_angryStandRight
	.global MetaSprite_businessMan_angryWalkRight
	.global MetaSprite_businessMan_angryWaitRight
	.global MetaSprite_businessMan_fightingStandRight
	.global MetaSprite_businessMan_fightingWalkRight
	.global MetaSprite_businessMan_fightingWaitRight
	.global MetaSprite_businessMan_normalStandLeft
	.global MetaSprite_businessMan_normalWalkLeft
	.global MetaSprite_businessMan_normalWaitLeft
	.global MetaSprite_businessMan_stressedStandLeft
	.global MetaSprite_businessMan_stressedWalkLeft
	.global MetaSprite_businessMan_stressedWaitLeft
	.global MetaSprite_businessMan_angryStandLeft
	.global MetaSprite_businessMan_angryWalkLeft
	.global MetaSprite_businessMan_angryWaitLeft
	.global MetaSprite_businessMan_fightingStandLeft
	.global MetaSprite_businessMan_fightingWalkLeft
	.global MetaSprite_businessMan_fightingWaitLeft

.global MetaSpriteFrameTable_fighting
.global MetaSprite_fightingCloud
	.global MetaSprite_fightingCloud_frame0
	.global MetaSprite_fightingCloud_frame1
	.global MetaSprite_fightingCloud_frame2
	.global MetaSprite_fightingCloud_frame3
	.global MetaSprite_fightingCloud_frame4

.global MetaSpriteFrameTable_leftRight
.global MetaSprite_wrongFloor0
	.global MetaSprite_wrongFloor0_left
	.global MetaSprite_wrongFloor0_right
.global MetaSprite_wrongFloor1
	.global MetaSprite_wrongFloor1_left
	.global MetaSprite_wrongFloor1_right
.global MetaSprite_lightingZap
	.global MetaSprite_lightingZap_left
	.global MetaSprite_lightingZap_right

