#!/usr/bin/env python3
"""Generate single-cycle BRR waveform samples for PICO-8 instruments on SPC700."""

import math
import struct

NUM_SAMPLES = 32  # samples per cycle (2 BRR blocks = 18 bytes)

def generate_waveform(instrument_id):
    """Generate 32 float samples (-1.0 to 1.0) for a PICO-8 instrument."""
    n = NUM_SAMPLES
    samples = []

    if instrument_id == 0:  # Triangle
        for i in range(n):
            t = i / n
            if t < 0.25:
                samples.append(t * 4)
            elif t < 0.75:
                samples.append(2 - t * 4)
            else:
                samples.append(t * 4 - 4)

    elif instrument_id == 1:  # Tilted Saw (asymmetric triangle)
        for i in range(n):
            t = i / n
            if t < 0.75:
                samples.append(t / 0.75 * 2 - 1)
            else:
                samples.append(1 - (t - 0.75) / 0.25 * 2)

    elif instrument_id == 2:  # Saw
        for i in range(n):
            samples.append(2 * i / n - 1)

    elif instrument_id == 3:  # Square (50% duty)
        for i in range(n):
            samples.append(1.0 if i < n // 2 else -1.0)

    elif instrument_id == 4:  # Pulse (25% duty)
        for i in range(n):
            samples.append(1.0 if i < n // 4 else -1.0)

    elif instrument_id == 5:  # Organ (fundamental + octave)
        for i in range(n):
            t = 2 * math.pi * i / n
            samples.append(0.7 * math.sin(t) + 0.3 * math.sin(2 * t))

    elif instrument_id == 6:  # Noise placeholder (DSP_NON handles actual noise)
        for i in range(n):
            samples.append(1.0 if i < n // 2 else -1.0)

    elif instrument_id == 7:  # Phaser (fundamental + slightly detuned)
        for i in range(n):
            t = 2 * math.pi * i / n
            samples.append(0.6 * math.sin(t) + 0.4 * math.sin(t * 1.02 + 0.5))

    # Normalize to [-1, 1]
    peak = max(abs(s) for s in samples) or 1.0
    samples = [s / peak for s in samples]
    return samples


def encode_brr_block(pcm_16, is_last=False, is_loop=False):
    """Encode 16 PCM samples (16-bit signed) into one 9-byte BRR block using filter 0."""
    best_shift = 0
    best_error = float('inf')
    best_nibbles = []

    for shift in range(13):
        nibbles = []
        total_error = 0
        for s in pcm_16:
            # Quantize
            if shift == 0:
                nib = max(-8, min(7, round(s)))
            else:
                nib = max(-8, min(7, round(s / (1 << shift))))
            nibbles.append(nib)
            decoded = nib << shift
            err = (decoded - s) ** 2
            total_error += err
        if total_error < best_error:
            best_error = total_error
            best_shift = shift
            best_nibbles = nibbles[:]

    # Header: shift[7:4] | filter[3:2] | loop[1] | end[0]
    flags = 0
    if is_last:
        flags |= 0x01  # end flag
    if is_loop:
        flags |= 0x03  # end + loop flags
    header = (best_shift << 4) | (0 << 2) | flags  # filter 0

    # Pack nibbles: high nibble = even sample, low nibble = odd sample
    data = []
    for i in range(0, 16, 2):
        hi = best_nibbles[i] & 0x0F
        lo = best_nibbles[i + 1] & 0x0F
        data.append((hi << 4) | lo)

    return bytes([header] + data)


def generate_brr(samples_float):
    """Generate BRR data for a 32-sample waveform (2 blocks, looping)."""
    pcm = [int(s * 32767) for s in samples_float]
    block0 = encode_brr_block(pcm[0:16], is_last=False)
    block1 = encode_brr_block(pcm[16:32], is_last=True, is_loop=True)
    return block0 + block1


INSTRUMENT_NAMES = [
    "triangle", "tilted_saw", "saw", "square",
    "pulse", "organ", "noise", "phaser"
]


def generate_header():
    """Generate brrSamples.h with all 8 instrument waveforms."""
    lines = []
    lines.append("// Auto-generated BRR waveform samples for PICO-8 instruments")
    lines.append("// Each sample is 32 samples/cycle = 2 BRR blocks = 18 bytes")
    lines.append("// Generated by generate_brr_samples.py")
    lines.append("")
    lines.append("#include <stdint.h>")
    lines.append("")

    for inst_id in range(8):
        name = INSTRUMENT_NAMES[inst_id]
        waveform = generate_waveform(inst_id)
        brr_data = generate_brr(waveform)

        lines.append(f"// Instrument {inst_id}: {name} ({len(brr_data)} bytes)")
        hex_bytes = ", ".join(f"0x{b:02X}" for b in brr_data)
        lines.append(f"static const uint8_t sample_{name}[] = {{ {hex_bytes} }};")
        lines.append("")

    # Also generate the pitch lookup table
    # For 32-sample waveforms: DSP_pitch = freq * 4096 * 32 / 32000 = freq * 4.096
    # PICO-8 formula (from fake-08): freq = 440 * 2^((key - 33) / 12)
    lines.append("// Pitch lookup table: PICO-8 pitch (0-63) -> 14-bit SPC700 DSP pitch")
    lines.append("// For 32-sample single-cycle waveforms")
    lines.append("// Formula: freq = 440 * 2^((pitch - 33) / 12), dsp_pitch = freq * 4.096")
    lines.append("static const uint16_t pitch_lut[64] = {")
    row = "    "
    for p in range(64):
        # PICO-8 key_to_freq: 440 * 2^((key - 33) / 12)
        # key 0 = C2 (65.4Hz), key 24 = C4 (261.6Hz), key 33 = A4 (440Hz)
        freq = 440.0 * (2 ** ((p - 33) / 12.0))
        dsp_pitch = int(freq * 4.096 + 0.5)
        dsp_pitch = max(0, min(0x3FFF, dsp_pitch))
        row += f"0x{dsp_pitch:04X}, "
        if (p + 1) % 8 == 0:
            lines.append(row)
            row = "    "
    if row.strip():
        lines.append(row)
    lines.append("};")
    lines.append("")

    return "\n".join(lines)


def main():
    import os
    spc_dir = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
                           "spc700")
    header_path = os.path.join(spc_dir, "brrSamples.h")

    content = generate_header()
    with open(header_path, "w") as f:
        f.write(content)
    print(f"Written {header_path}")

    # Print summary
    for inst_id in range(8):
        waveform = generate_waveform(inst_id)
        brr = generate_brr(waveform)
        print(f"  Instrument {inst_id} ({INSTRUMENT_NAMES[inst_id]}): {len(brr)} bytes")


if __name__ == "__main__":
    main()
