del mainBankZero.obj -f
del vectors.obj -f
del mainBankZero.bin -f
del mainBankZero.bin -f
del lib\initsnes.obj -f
del lib\kernel.obj -f
del mainBankZero.bnk -f
del mainBankZero.map -f
del imagedata.obj -f
del CrashHandler.obj -f
