
ROM_NAME    = unit_tests
CONFIG      = LOROM_1MBit
API_DIR     = ..
SOURCE_DIR  = .
RESOURCES_DIR = ../resources

API_MODULES  = reset-snes sfc-header block screen text text8x16 text8x8 math metasprite

include ../Makefile.in

